### ISSUE TITLE
mod_pushoff_apns:handle_info:178 connection to APNS failed: {keyfile,function_clause}

### ISSUE THREAD

**Issue by nazreenyusof** [proger/mod_pushoff#10]
i already extract a certificates from apples with private key. when i convert it to pem combine certificates and private key. it appears the error.

please help.

**Comment by nazreenyusof** [comment]
i used 
erlang /OTP 21
ejabberd 19.05
ubuntu 18.04

**Comment by proger** [comment]
Hi,

This module currently supports only ejabberd 18.01.

I am open to PRs that work with newer versions though.
