### ISSUE TITLE
Error: {compilation_failed,"/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl"} ejabberd 20.04

### ISSUE THREAD

**Issue by bulletvullet** [proger/mod_pushoff#11]
Hi there, I've tried to install module inside docker container based on docker ecs 20.04 image and got issue:
`Error: {compilation_failed,"/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl"}`
Traceback:
`/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/ebin/mod_pushoff.bea#: error writing file: no such file or directory
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl:25: Warning: undefined callback function mod_doc/0 (behaviour 'gen_mod')
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl:25: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl:27: Warning: export_all flag enabled - all functions will be exported
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/ebin/mod_pushoff_apns.bea#: error writing file: no such file or directory
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff_apns.erl:26: Warning: export_all flag enabled - all functions will be exported
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/ebin/mod_pushoff_fcm.bea#: error writing file: no such file or directory
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff_fcm.erl:28: Warning: export_all flag enabled - all functions will be exported
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/ebin/mod_pushoff_mnesia.bea#: error writing file: no such file or directory
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/ebin/mod_pushoff_utils.bea#: error writing file: no such file or directory
/home/ejabberd/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff_utils.erl:25: Warning: export_all flag enabled - all functions will be exported
Error: error
`
Any ideas? Thanks
![Screenshot from 2020-05-25 15-14-59](https://user-images.githubusercontent.com/10546091/82811917-8c0c7400-9e9a-11ea-8ba2-5633befdb249.png)

**Comment by proger** [comment]
Hi,

This module currently supports only ejabberd 18.01.

I am open to PRs that work with newer versions though.
