### ISSUE TITLE
How to Test server side Configuration is OK or Not

### ISSUE THREAD

**Issue by masterhydra** [proger/mod_pushoff#13]
Hello Team,

Thanks for provide this module, I have use ejabberd 18.01 compiled from source, Erlang/OTP 20 in Ubuntu VERSION="18.04.4 LTS (Bionic Beaver)"

I use this module but not able to verify my server side configuration is ok or not, is there any method to check my server side configuration is perfectly working or not.

I check on browser by hit this url but it is not responding http://push.192.168.95.3

 I need to check. just like http://192.168.95.3:5280/bosh or http://192.168.95.3:5280/ws

connection between my server to apns server is perfect from certificate.
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert /etc/ssl/private/apns_example_app_sandbox.pem

Output : - CONNECTED(00000005)

Kindly support my configuration is mentioned below.

[ejabberd.yml.txt](https://github.com/proger/mod_pushoff/files/5123587/ejabberd.yml.txt)

**Comment by proger** [comment]
Hello and thanks for your issue!

The best way to check configuration at the moment is to use an app that is able to send a registration message to one of the backends and go offline to receive one of the messages.
