### ISSUE TITLE
Can you add all improvements from forks

### ISSUE THREAD

**Issue by Neustradamus** [proger/mod_pushoff#15]
@proger: Can you add all improvements from forks?
- https://github.com/proger/mod_pushoff/network/members

From:
- @dav1nci
- @mandayugana
- @liangdefeng
- @loguntsov

Thanks in advance.

**Comment by proger** [comment]
Thanks for your issue @Neustradamus!

I'm glad that there's a network of mod_pushoff users that were able to use this code for their use cases.

I have a particularly narrow use case for this plugin but would love to accept PRs that do not radically change functionality or break client APIs unless necessary. Could you describe what particular improvements you'd like to see in mod_pushoff in separate issues?

**Comment by Neustradamus** [comment]
@proger: Thanks for your reply!

You have closed this ticket!

Here:
- https://github.com/dav1nci/mod_pushoff/branches
- https://github.com/mandayugana/mod_pushoff/branches
- https://github.com/liangdefeng/mod_pushoff/branches
- https://github.com/loguntsov/mod_pushoff/branches
