### ISSUE TITLE
Store FCM tokens in sql database

### ISSUE THREAD

**Issue by reyhanehpahlevan** [proger/mod_pushoff#8]
Hi,
Thanks for your great work! I wonder where the FCM tokens will be stored and how I can store them in my psql database besides the other feature of each account?

Best,
Reyhaneh

**Comment by proger** [comment]
Hi!

Feel free to implement your own storage backend replacing `mod_pushoff_mnesia`, https://github.com/proger/mod_pushoff/blob/master/src/mod_pushoff_mnesia.erl#L5

Unfortunately I do not plan to support multiple storage backends for this version of the plugin.
