### ISSUE TITLE
mod_options is not defined error in ejabberd 19.9.1

### ISSUE THREAD

**Issue by reyhanehpahlevan** [proger/mod_pushoff#9]
Hi,
I'm trying to use this module for a couple of days but after configuring the  "ejabberd.yml", the server can not start and  the error is:

> 2020-01-23 09:28:20.533396+00:00 [critical] Failed to start ejabberd application: Invalid value of option modules: third-party ejabberd module 'mod_pushoff' doesn't export function mod_options/1. If it's really a ejabberd module, consider to upgrade it

I add the following lines in the "mod_pushoff/src/mod_pushoff.erl" file 

```bash
mod_options(_) ->
    [backends].
```

and I got this error:

> 2020-01-23 09:18:39.662878+00:00 [critical] Internal error of module mod_pushoff has occurred during start:
> ** Options: #{backends =>
>                   [{backend_config,fcm,
>                        {fcm_config,<<"https://fcm.googleapis.com/fcm/send">>,
>                            <<"AAAAw6t-4cw:APA91bEESZ7SrdV4MfizLXuiRT....">>}}]}
> ** exception error: no function clause matching 
>                   proplists:get_value(backends,
>                                       #{backends =>
>                                          [{backend_config,fcm,
>                                            {fcm_config,
>                                             <<"https://fcm.googleapis.com/fcm/send">>,
>                                             <<"AAAAw6t-4cw:APA91bEESZ7SrdV4MfizLXuiRT6aXs5bM.....">>}}]},
>                                       undefined) (proplists.erl, line 215)
>      in function  mod_pushoff:start/2 (/home/ubuntu/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl, line 181)
   in call from gen_mod:start_module/4 (src/gen_mod.erl, line 155)
   in call from lists:foreach/2 (lists.erl, line 1338)
   in call from gen_mod:start_link/0 (src/gen_mod.erl, line 82)
   in call from supervisor:do_start_child_i/3 (supervisor.erl, line 379)
   in call from supervisor:do_start_child/2 (supervisor.erl, line 365)
   in call from supervisor:'-start_children/2-fun-0-'/3 (supervisor.erl, line 349)
2020-01-23 09:36:08.825706+00:00 [critical] ejabberd initialization was aborted because a module start failed.

I would be really thankful if you could help me with this error.

Best,
Reyhaneh

**Comment by skumarm** [comment]
> Hi,
> I'm trying to use this module for a couple of days but after configuring the "ejabberd.yml", the server can not start and the error is:
> 
> > 2020-01-23 09:28:20.533396+00:00 [critical] Failed to start ejabberd application: Invalid value of option modules: third-party ejabberd module 'mod_pushoff' doesn't export function mod_options/1. If it's really a ejabberd module, consider to upgrade it
> 
> I add the following lines in the "mod_pushoff/src/mod_pushoff.erl" file
> 
> ```shell
> mod_options(_) ->
>     [backends].
> ```
> 
> and I got this error:
> 
> > 2020-01-23 09:18:39.662878+00:00 [critical] Internal error of module mod_pushoff has occurred during start:
> > ** Options: #{backends =>
> > [{backend_config,fcm,
> > {fcm_config,<<"https://fcm.googleapis.com/fcm/send">>,
> > <<"AAAAw6t-4cw:APA91bEESZ7SrdV4MfizLXuiRT....">>}}]}
> > ** exception error: no function clause matching
> > proplists:get_value(backends,
> > #{backends =>
> > [{backend_config,fcm,
> > {fcm_config,
> > <<"https://fcm.googleapis.com/fcm/send">>,
> > <<"AAAAw6t-4cw:APA91bEESZ7SrdV4MfizLXuiRT6aXs5bM.....">>}}]},
> > undefined) (proplists.erl, line 215)
> > in function  mod_pushoff:start/2 (/home/ubuntu/.ejabberd-modules/sources/mod_pushoff/src/mod_pushoff.erl, line 181)
> > in call from gen_mod:start_module/4 (src/gen_mod.erl, line 155)
> > in call from lists:foreach/2 (lists.erl, line 1338)
> > in call from gen_mod:start_link/0 (src/gen_mod.erl, line 82)
> > in call from supervisor:do_start_child_i/3 (supervisor.erl, line 379)
> > in call from supervisor:do_start_child/2 (supervisor.erl, line 365)
> > in call from supervisor:'-start_children/2-fun-0-'/3 (supervisor.erl, line 349)
> > 2020-01-23 09:36:08.825706+00:00 [critical] ejabberd initialization was aborted because a module start failed.
> 
> I would be really thankful if you could help me with this error.
> 
> Best,
> Reyhaneh

Hi, 
I am checking this module with ejabberd - 20.01.

Iam also getting this kind of warnings...

> mod_pushoff/src/mod_pushoff.erl:25: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')
> mod_pushoff/src/mod_pushoff.erl:27: Warning: export_all flag enabled - all functions will be exported
> mod_pushoff/src/mod_pushoff_apns.erl:26: Warning: export_all flag enabled - all functions will be exported
> mod_pushoff/src/mod_pushoff_fcm.erl:28: Warning: export_all flag enabled - all functions will be exported
> mod_pushoff/src/mod_pushoff_utils.erl:25: Warning: export_all flag enabled - all functions will be exported

And while restarting ejabberd, getting this error and server is not restarting...

> Failed to start ejabberd application: Invalid value of option modules: unknown ejabberd module: mod_pushoff. Did you mean mod_pushoff?

@proger , Please help me to get rid of this error...

**Comment by proger** [comment]
Hi,

This module currently supports only ejabberd 18.01.

I am open to PRs that work with newer versions though.
